//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.17 at 04:03:39 PM IST 
//


package com.example.pojo;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.example.pojo package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _PurchaseOrder_QNAME = new QName("http://tempuri.org/PurchaseOrderSchema.xsd", "PurchaseOrder");
    private final static QName _Cat_QNAME = new QName("", "cat");
    private final static QName _Dog_QNAME = new QName("", "dog");
    private final static QName _Pet_QNAME = new QName("", "pet");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.example.pojo
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PurchaseOrderType }
     * 
     */
    public PurchaseOrderType createPurchaseOrderType() {
        return new PurchaseOrderType();
    }

    /**
     * Create an instance of {@link USAddress }
     * 
     */
    public USAddress createUSAddress() {
        return new USAddress();
    }

    /**
     * Create an instance of {@link Cat }
     * 
     */
    public Cat createCat() {
        return new Cat();
    }

    /**
     * Create an instance of {@link PetType }
     * 
     */
    public PetType createPetType() {
        return new PetType();
    }

    /**
     * Create an instance of {@link Dog }
     * 
     */
    public Dog createDog() {
        return new Dog();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PurchaseOrderType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/PurchaseOrderSchema.xsd", name = "PurchaseOrder")
    public JAXBElement<PurchaseOrderType> createPurchaseOrder(PurchaseOrderType value) {
        return new JAXBElement<PurchaseOrderType>(_PurchaseOrder_QNAME, PurchaseOrderType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Cat }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "cat", substitutionHeadNamespace = "", substitutionHeadName = "pet")
    public JAXBElement<Cat> createCat(Cat value) {
        return new JAXBElement<Cat>(_Cat_QNAME, Cat.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Dog }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "dog", substitutionHeadNamespace = "", substitutionHeadName = "pet")
    public JAXBElement<Dog> createDog(Dog value) {
        return new JAXBElement<Dog>(_Dog_QNAME, Dog.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PetType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "pet")
    public JAXBElement<PetType> createPet(PetType value) {
        return new JAXBElement<PetType>(_Pet_QNAME, PetType.class, null, value);
    }

}
